"""Security, session tokens, and admin endpoint access control."""

import hashlib
import hmac
import logging
import time
from typing import Optional
from fastapi import Request, HTTPException, status
from .config import settings

logger = logging.getLogger(__name__)


def generate_admin_session_token() -> str:
    """Generate a signed, time-bound session token for the web dashboard."""
    ts = str(int(time.time()))
    payload = f"admin_session:{ts}".encode("utf-8")
    sig = hmac.new(settings.admin_secret_key.encode("utf-8"), payload, hashlib.sha256).hexdigest()
    return f"{ts}.{sig}"


def verify_admin_session_token(token: str, max_age_seconds: int = 86400 * 7) -> bool:
    """Verify signed session token from web dashboard."""
    if not token or "." not in token:
        return False
    parts = token.split(".", 1)
    ts_str, sig = parts[0], parts[1]
    try:
        ts = int(ts_str)
        if time.time() - ts > max_age_seconds:
            return False  # Expired
    except ValueError:
        return False

    payload = f"admin_session:{ts_str}".encode("utf-8")
    expected_sig = hmac.new(settings.admin_secret_key.encode("utf-8"), payload, hashlib.sha256).hexdigest()
    return hmac.compare_digest(expected_sig, sig)


async def verify_admin_access(request: Request):
    """
    Dependency protecting /api/admin/* endpoints.
    Allows:
    1. Valid X-Admin-Key matching settings.admin_secret_key.
    2. Valid X-Admin-Token or cookie admin_session generated by GET /.
    3. Blocks cross-origin CSRF/leakage attempts.
    """
    # Check 1: Explicit API key in header
    api_key = request.headers.get("X-Admin-Key") or request.headers.get("x-admin-key")
    if api_key and hmac.compare_digest(api_key.strip(), settings.admin_secret_key.strip()):
        return True

    # Check 2: Bearer token in Authorization header
    auth_header = request.headers.get("Authorization") or ""
    if auth_header.startswith("Bearer "):
        bearer_token = auth_header[7:].strip()
        if hmac.compare_digest(bearer_token, settings.admin_secret_key.strip()) or verify_admin_session_token(bearer_token):
            return True

    # Check 3: Web Dashboard Session Token (X-Admin-Token or cookie)
    session_token = request.headers.get("X-Admin-Token") or request.cookies.get("admin_session")
    if session_token and verify_admin_session_token(session_token):
        # Additional check: Prevent cross-site request forgery
        sec_fetch_site = request.headers.get("sec-fetch-site")
        if sec_fetch_site and sec_fetch_site.lower() == "cross-site":
            logger.warning("Blocked cross-site admin request from %s", request.headers.get("origin"))
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail="Acesso bloqueado: requisição cross-site não permitida."
            )
        return True

    # If neither matches, deny access
    logger.warning("Unauthorized access attempt to admin endpoint %s from %s", request.url.path, request.client.host if request.client else "unknown")
    raise HTTPException(
        status_code=status.HTTP_403_FORBIDDEN,
        detail="Acesso administrativo restrito. Autenticação necessária via X-Admin-Key ou sessão válida."
    )
